send("curing off")
ataxiaEcho("System has been "..(ataxia.settings.paused and "<red>paused." or "<green>unpaused."))
send("clearqueue all")
send("setalias kickass unwield shield/wield longsword left/behead "..target)
send("queue addclear free kickass")
