ataxiaEcho("Aliases for magi specific things.")
cecho("\n<green> VIBE <white>(vibration) <DimGrey>toggle usage of <x> vibe.")
cecho("\n<green> EVIBE <DimGrey>embeds wanted vibrations.")
echo("\n")
ataxiaEcho("Aliases for stormhammering.")
cecho("\n<green> SHRT <DimGrey>Stormhammers target + 2 others of the same city.")
cecho("\n<green> SHRE <DimGrey>Stormhammers target + 2 others on your enemy list.")
echo("\n")
ataxiaEcho("Note: lowercase for aliases.")
