--[[
  LEVI Configuration Example
  
  Copy this file to config/user_config.lua and customize your settings.
  Do not edit this file directly - it serves as a template.
]]--

local config = {}

-- ============================================================================
-- GENERAL SETTINGS
-- ============================================================================

config.general = {
  -- Enable or disable the entire system
  enabled = true,
  
  -- System command prefix (e.g., /levi help)
  command_prefix = "/levi",
  
  -- Debug mode: shows additional logging
  debug = false,
  
  -- Your character's class (used for class-specific features)
  -- Options: "runewarden", "paladin", "infernal", "druid", etc.
  character_class = "runewarden",
  
  -- Auto-start system on login
  auto_start = true,
}

-- ============================================================================
-- CURING SETTINGS
-- ============================================================================

config.curing = {
  -- Enable automatic curing
  enabled = true,
  
  -- Curing method preferences (in order of preference)
  methods = {
    "herb",
    "salve",
    "pipe",
    "focus",
    "tree",
    "passive"
  },
  
  -- Health/mana sipping thresholds (percentage)
  sip_health_threshold = 70,
  sip_mana_threshold = 70,
  
  -- Moss healing threshold
  moss_threshold = 65,
  
  -- Priority overrides for specific afflictions
  -- Higher number = higher priority (1-100)
  priorities = {
    -- Critical (life-threatening)
    anorexia = 95,
    asthma = 90,
    slickness = 90,
    
    -- High priority (major combat impact)
    paralysis = 85,
    impatience = 80,
    prone = 80,
    
    -- Medium priority
    clumsiness = 60,
    nausea = 55,
    weariness = 55,
    
    -- Low priority
    lovers = 30,
    peace = 30,
  },
  
  -- Auto-use tree tattoo
  auto_tree = true,
  tree_affliction_threshold = 3,  -- Use tree when this many affs
  
  -- Auto-use focus
  auto_focus = true,
  focus_on_mental = true,
}

-- ============================================================================
-- TRACKING SETTINGS
-- ============================================================================

config.tracking = {
  -- Track your own afflictions
  track_self = true,
  
  -- Track enemy afflictions (requires visibility)
  track_enemy = true,
  
  -- Track defenses
  track_defenses = true,
  
  -- Track resources (health, mana, endurance, willpower)
  track_resources = true,
  
  -- Balance tracking
  track_balances = {
    balance = true,
    equilibrium = true,
    class_balance = true,  -- Class-specific balances
  },
  
  -- Affliction confirmation timeout (seconds)
  -- If affliction not confirmed within this time, assume cured
  aff_timeout = 30,
}

-- ============================================================================
-- OFFENSE SETTINGS
-- ============================================================================

config.offense = {
  -- Enable automatic offense
  enabled = false,  -- Set to true to enable
  
  -- Offense mode
  -- Options: "manual", "semi-auto", "full-auto"
  mode = "semi-auto",
  
  -- Default target
  default_target = "",
  
  -- Auto-target on attack
  auto_target = false,
  
  -- Ability queue settings
  queue = {
    enabled = true,
    max_size = 10,
    -- Execute queued abilities on balance
    auto_execute = true,
  },
  
  -- Strategy selection
  -- Options: "damage", "afflictions", "prep", "custom"
  strategy = "afflictions",
  
  -- Class-specific offense settings
  class_settings = {
    -- Example for Knight classes
    knight = {
      venom_priority = {"curare", "kalmia", "prefarar", "xentio"},
      toxin_priority = {"epseth", "epteth", "nechamandra"},
      auto_envenom = true,
    },
  },
}

-- ============================================================================
-- UI SETTINGS
-- ============================================================================

config.ui = {
  -- Enable UI components
  enabled = true,
  
  -- Theme
  -- Options: "dark", "light", "custom"
  theme = "dark",
  
  -- Main window position and size
  main_window = {
    x = 0,
    y = 0,
    width = 400,
    height = 300,
  },
  
  -- Show affliction list
  show_afflictions = true,
  affliction_window = {
    x = 0,
    y = 300,
    width = 300,
    height = 200,
  },
  
  -- Show balance indicators
  show_balances = true,
  balance_window = {
    x = 0,
    y = 500,
    width = 300,
    height = 100,
  },
  
  -- Show target information
  show_target = true,
  target_window = {
    x = 400,
    y = 0,
    width = 300,
    height = 200,
  },
  
  -- Gauges (health, mana, etc.)
  gauges = {
    enabled = true,
    show_percentage = true,
    show_numbers = true,
    height = 20,
  },
  
  -- Colors (RGB or hex)
  colors = {
    health = "#ff0000",
    mana = "#0000ff",
    endurance = "#ffff00",
    willpower = "#00ffff",
    
    -- Affliction severity colors
    critical = "#ff0000",
    high = "#ff8800",
    medium = "#ffff00",
    low = "#88ff88",
  },
  
  -- Notifications
  notifications = {
    enabled = true,
    -- Show notification on specific events
    on_critical_aff = true,
    on_death = true,
    on_target_death = true,
  },
}

-- ============================================================================
-- ALIASES AND KEYBINDINGS
-- ============================================================================

config.aliases = {
  -- Quick toggle commands
  toggle_system = "levi",
  toggle_curing = "cc",
  toggle_offense = "oo",
  
  -- Target commands
  set_target = "tt",
  next_target = "nt",
  clear_target = "ct",
  
  -- Status commands
  status = "st",
  reset = "rst",
}

config.keybindings = {
  -- Example keybindings (F1-F12, Ctrl+key, etc.)
  -- Format: {key = "F1", modifier = "ctrl", command = "..."}
  
  -- F1: Toggle system
  {key = "F1", command = "/levi toggle"},
  
  -- F2: Target nearest enemy
  {key = "F2", command = "/levi target nearest"},
  
  -- F12: Emergency stop (disable all automation)
  {key = "F12", command = "/levi emergency_stop"},
}

-- ============================================================================
-- ADVANCED SETTINGS
-- ============================================================================

config.advanced = {
  -- Performance settings
  performance = {
    -- Event throttling (milliseconds)
    event_throttle = 50,
    
    -- Maximum events per second
    max_events_per_second = 100,
    
    -- Cache size for tracking data
    cache_size = 1000,
  },
  
  -- Logging
  logging = {
    enabled = true,
    log_level = "INFO",  -- Options: "DEBUG", "INFO", "WARN", "ERROR"
    log_file = "logs/levi.log",
    max_log_size = 10485760,  -- 10 MB
  },
  
  -- Integration with other systems
  integration = {
    -- Server-side curing (if you have server-side enabled)
    use_serverside_curing = false,
    
    -- GMCP usage
    use_gmcp = true,
  },
}

-- ============================================================================
-- CUSTOM SCRIPTS
-- ============================================================================

-- You can add custom initialization code here
config.custom_init = function()
  -- This function runs after the system initializes
  -- Add your custom setup here
  
  -- Example:
  -- print("LEVI loaded with custom configuration!")
end

-- Custom event handlers
config.custom_handlers = {
  -- Example: Custom handler for when you gain an affliction
  on_affliction_gained = function(affliction)
    -- Custom logic here
  end,
  
  -- Example: Custom handler for when you cure an affliction
  on_affliction_cured = function(affliction)
    -- Custom logic here
  end,
}

-- ============================================================================
-- EXPORT
-- ============================================================================

return config
