-- unnamed > For Levi > mudlet-mapper > Mudlet Mapper > Game-specific > Imperian > register_imperians_envdata

function register_imperians_envdata(_, game)
  if game ~= "Imperian" then return end
  mmp.envids =
  {
    ["a sheltered dell"]        = 68,
    ["Arcane Temple"]           = 66,
    ["Blackened Lands"]         = 58,
    ["Blackstone Dungeon"]      = 65,
    ["Blackstone Keep"]         = 62,
    ["Constructed underground"] = 2,
    ["Dark Forest"]             = 1,
    ["Deep Ocean"]              = 24,
    ["Desert Ruins"]            = 38,
    ["Dwarven city"]            = 18,
    ["Forestal Council"]        = 44,
    ["Frozen Bog"]              = 76,
    ["Lake of Fire"]            = 56,
    ["Natural underground"]     = 3,
    ["Noble Bar"]               = 53,
    ["Noble Chambers"]          = 51,
    ["Rocky Shore"]             = 77,
    ["Sylayan city"]            = 19,
    ["Tainted Underground"]     = 35,
    ["Tainted Water"]           = 39,
    ["Underground Lake"]        = 36,
    ["Vast Ocean"]              = 26,
    ["Wetlands Village"]        = 64,
    ["within a tent"]           = 69,
    Academia                    = 42,
    Acropolis                   = 33,
    Beach                       = 5,
    Blighted                    = 74,
    bog                         = 73,
    Catacombs                   = 63,
    Church                      = 54,
    Cliffs                      = 67,
    Crags                       = 32,
    Desert                      = 6,
    Docks                       = 30,
    Farmland                    = 41,
    Forest                      = 4,
    Freshwater                  = 22,
    Garden                      = 21,
    garrison                    = 71,
    Grasslands                  = 7,
    Graveyard                   = 46,
    Hills                       = 9,
    Jungle                      = 17,
    Mountains                   = 14,
    Nobility                    = 50,
    Ocean                       = 20,
    Path                        = 11,
    Polar                       = 27,
    Pond                        = 49,
    pyramid                     = 72,
    quarry                      = 70,
    River                       = 10,
    Road                        = 12,
    Ruins                       = 37,
    Scrublands                  = 78,
    Sewer                       = 23,
    Swamp                       = 15,
    Temple                      = 57,
    Tower                       = 79,
    transportation              = 48,
    Tundra                      = 16,
    Underworld                  = 28,
    Urban                       = 8,
    Valley                      = 13,
    Villa                       = 75,
    Village                     = 47,
    Village                     = 55,
    Volcano                     = 59,
    Warrens                     = 31,
  }

  mmp.waterenvs = {}
  local waterids = { "River", "Ocean", "Deep Ocean", "Vast Ocean", "Underground Lake", "Tainted Water", "Lake of Fire" }
  for i = 1, #waterids do mmp.waterenvs[mmp.envids[waterids[i]]] = true end

  mmp.envidsr = {};
  for name, id in pairs(mmp.envids) do mmp.envidsr[id] = name end
end