--[[mudlet
type: script
name: Boon Seed Catalogue
hierarchy:
- Levi_Ataxia
- Ataxia
- Mnemosyne
attributes:
  isActive: 'yes'
  isFolder: 'no'
packageName: ''
]]--

--[[
    ============================================================================
    MNEMOSYNE BOON SEED CATALOGUE
    ============================================================================
    294 boons, seeded so the database is useful on day one instead of only for
    boons this character has personally been offered.

    SOURCE: the community catalogue at
    https://mediaresachaea.github.io/mnemosyne-boons/ -- captured in-game by the
    `mnemosyne.lua` Mudlet tracker (Achaea, Treyal), snapshot 2026-07-17 22:59 UTC.
    Not our data; credited here because it should be.

    MERGED, NEVER IMPOSED. This goes through M._boonDbMerge, which only fills
    fields that are empty -- so anything YOU have seen in-game always wins, a
    later in-game sighting can enrich a seeded row, and re-loading changes
    nothing. A seed that overwrote observed data would be worse than no seed.

    Descriptions and rarity only. The flavour quotes are ~50% of the source
    file's bulk and nothing reads them; echoDescription is kept where present
    because it says what a second copy of the boon does.
    ============================================================================
]]--

ataxia.mnemosyne = ataxia.mnemosyne or {}
local M = ataxia.mnemosyne

M.BOON_SEED = {
  ["Aarashi Tactics"] = { description = "The cooldown for commanding your eagle to rake a denizen is reduced by 66%.", rarity = "common" },
  ["Abundance"] = { description = "Defeating a denizen has a 10% chance of granting you the panacea defence for 25 seconds.", rarity = "common" },
  ["Academician"] = { description = "You are immune to the stupidity affliction.", rarity = "legendary" },
  ["Acidbreath"] = { description = "Your draconic blast attack is imbued with a Black Dragon's breath, granting it a 20% chance to afflict your foe with sensitivity.", rarity = "common" },
  ["Acrobat"] = { description = "Tumbling completes instantly but incurs a 50% increased balance cost.", rarity = "common" },
  ["Adroit"] = { description = "You are immune to the clumsiness affliction.", rarity = "common" },
  ["Alacritous"] = { description = "You are immune to the aeon affliction.", rarity = "rare" },
  ["Algiz Protect"] = { description = "While affected by Algiz, all damage you take is reduced by an additional 10%.", rarity = "common" },
  ["Aloofness"] = { description = "Your sireni heritage grants you immunity to transfixion.", rarity = "rare" },
  ["Antidexterous"] = { description = "There is a 5% chance you make the denizen you are attacking clumsy for 5 seconds.", rarity = "uncommon", echo = "There is a 10% chance you make the denizen you are attacking clumsy for 5 seconds." },
  ["Argent Scales"] = { description = "Gain 25% resistance to electric damage.", rarity = "common", echo = "Gain 50% resistance to electric damage." },
  ["Army of the Dead"] = { description = "When summoning the hands of the grave, you will deal damage to all denizens in the location.", rarity = "rare" },
  ["Ascetic"] = { description = "You are immune to the addiction affliction.", rarity = "common" },
  ["Ashaxei's Mirror"] = { description = "When taking elemental damage greater than 20% of your health, gain 1 reflections.", rarity = "uncommon" },
  ["Aspect of Kkractle"] = { description = "Commanding a summoned ashbeast to surge now deals fire damage to all denizens in your location.", rarity = "rare" },
  ["Assassin's Blade"] = { description = "When hidden from sight, your backstab will resolve instantly without a need to channel.", rarity = "rare" },
  ["Atheist"] = { description = "You are immune to the hellsight affliction.", rarity = "common" },
  ["Aurum Scales"] = { description = "Gain 25% resistance to psychic damage.", rarity = "common", echo = "Gain 50% resistance to psychic damage." },
  ["Azure Scales"] = { description = "Gain 25% resistance to cold damage.", rarity = "common", echo = "Gain 50% resistance to cold damage." },
  ["Baron's Bro"] = { description = "When you critically strike, there is a low chance that your attack will invoke Baron Balam Agab, summoning a squad of ogre goons to lay waste to your enemies. This may only occur once every 20 seconds.", rarity = "rare" },
  ["Battle-Scarred"] = { description = "The memory of the War Veil grants 10% physical resistance.", rarity = "common", echo = "The memory of the War Veil grants 30% physical resistance." },
  ["Battlemaster's Fury"] = { description = "Your balance recovers 30% faster, but you can no longer be healed above 30% health.", rarity = "rare" },
  ["Beeline"] = { description = "You may now utilise prism tattoos against non-boss denizens.", rarity = "common" },
  ["Berkana Surround"] = { description = "Berkana now additionally reduces your mana, willpower, and endurance costs by 5%.", rarity = "common" },
  ["Blade of Celestia"] = { description = "Smiting a denizen has a chance to invoke the wrath of Celestia, summoning forth an angelic manifestation to visit devastation upon your enemies.", rarity = "uncommon" },
  ["Bladed Reflexes"] = { description = "You take 20% reduced damage while your reflexes are augmented with Shin energy via your Shindo augment ability.", rarity = "uncommon" },
  ["Blood Pact"] = { description = "You deal 25% more damage but all mana costs now cost health.", rarity = "uncommon" },
  ["Bloodscent"] = { description = "You sense out your prey upon entering a ripple.", rarity = "common" },
  ["Blossom of Pain"] = { description = "Your sternum strikes deal an additional 300% damage.", rarity = "common" },
  ["Bodybuilder"] = { description = "Each kill on a denizen grants you 3 additional maximum health but you lose 2 points of maximum mana.", rarity = "rare", echo = "Each kill on a denizen grants you 6 additional maximum health but you lose 4 points of maximum mana." },
  ["Boon of the Lord Dragon"] = { description = "Your firelash deals 100% increased damage against denizens.", rarity = "common", echo = "Your firelash deals 200% increased damage against denizens." },
  ["Borrowed Power"] = { description = "Your critical hits can now reach plane-razing level without requiring paragons or the Psion class. This does not stack with those effects, however.", rarity = "rare" },
  ["Boulder"] = { description = "You can no longer move normally, but when tumbling into a room, you will deal significant damage to all denizens present.", rarity = "rare" },
  ["Brawler"] = { description = "Your basic punches, kicks, and headslams deal 1000% more damage.", rarity = "rare" },
  ["Candour"] = { description = "You are immune to the blackout affliction by the clarity of the Lightbringer.", rarity = "rare" },
  ["Careless Whisperer"] = { description = "You are immune to masochism, hallucinations, and paranoia, and you always walk with a zealous warding against the Outer Cold.", rarity = "rare" },
  ["Catastrophic Mixture"] = { description = "You will no longer die when under the effects of destructive serum, but failing to secure a kill within 30 seconds of your last will cause you to be blacked out and suffer a reduction of 10 to all stats for the remainder of the ripple.", rarity = "legendary" },
  ["Catlike Reflexes"] = { description = "Your rajamalan heritage grants you 10% faster balance recovery.", rarity = "rare" },
  ["Cavalry"] = { description = "When you are mounted, you gain 2 celerity and you deal 10% more damage, but you can no longer walk normally.", rarity = "common" },
  ["Celestial"] = { description = "While possessing the hunt heresy defence, you are blessed with a Celestial aura that strikes at denizens you do, dealing holy fire damage to them. This effect can only occur once every 5 seconds.", rarity = "legendary" },
  ["Ceylon's Resolve"] = { description = "Your Maya figurine is now effective on all critical hits.", rarity = "legendary" },
  ["Child of Chaos"] = { description = "The Wayward Heir lends your attacks a 10% chance to deliver a random battlerage affliction to your target.", rarity = "rare" },
  ["Child of the Sky"] = { description = "Your atavian heritage allows you to fly without consuming, but still requiring, balance.", rarity = "common" },
  ["Cleave"] = { description = "Your attacks deal a small amount of splash damage to another random denizen in the location.", rarity = "rare", echo = "Your attacks deal a small amount of splash damage to another random denizen in the location." },
  ["Coarse Flesh"] = { description = "You are immune to slickness, but suffer permanent timeflux.", rarity = "rare" },
  ["Conductivity"] = { description = "When you take electric damage, your aqueous form will conduct the electricity to strike all denizens present.", rarity = "rare" },
  ["Conqueror"] = { description = "The unflinching will of Malevolence causes you to deal 15% more damage to enemies whose health percent is lower than yours.", rarity = "rare" },
  ["Convocation"] = { description = "You may now use brazier tattoos on non-boss denizens, but your brazier tattoo incurs a 1 minutes cooldown.", rarity = "rare" },
  ["Corrupted Blood"] = { description = "Your poison resistance is increased by 66% but you suffer permanent nausea.", rarity = "common" },
  ["Corrupted Breath"] = { description = "Your asphyxiation resistance is increased by 66% but you suffer permanent manaleech.", rarity = "common" },
  ["Corrupted Cold"] = { description = "Your cold resistance is increased by 66%, but you suffer permanent dehydration and tenderskin.", rarity = "common" },
  ["Corrupted Current"] = { description = "Your electric resistance is increased by 66% but you suffer permanent fulmination.", rarity = "common" },
  ["Corrupted Flesh"] = { description = "Your fire resistance is increased by 66% but you suffer permanent itching.", rarity = "common" },
  ["Corrupted Lineage"] = { description = "You may now select boons from any race, not solely those of your own race.", rarity = "rare" },
  ["Corrupted Mind"] = { description = "Your psychic resistance is increased by 66% but you suffer permanent guilt.", rarity = "common" },
  ["Crazy Horses"] = { description = "Commanding your steed to trample will deal massive blunt damage to all denizens present, but doing so will cause you to suffer a severe stun and lose 20% of your endurance.", rarity = "uncommon" },
  ["Creville's Legacy"] = { description = "You attack 20% faster but you have incurable dementia.", rarity = "common", echo = "You attack 25% faster but you have incurable dementia." },
  ["Crimson Scales"] = { description = "Gain 25% resistance to fire damage.", rarity = "common", echo = "Gain 50% resistance to fire damage." },
  ["Crusader"] = { description = "Empowered by your faith, your excision fervour defence grants you an additional 10% damage.", rarity = "common" },
  ["Crystal Blue Protection"] = { description = "Upon killing a denizen, you have a 10% chance of gaining the prismatic defence for 5 seconds.", rarity = "common" },
  ["Darkwalker"] = { description = "Defeating a denizen will render you hidden.", rarity = "common" },
  ["Death's Demise"] = { description = "Your health is increased to 133% of its normal maximum, but you can no longer benefit from the life-stealing effect of a death cape.", rarity = "common", echo = "Your health is increased to 177% of its normal maximum, but you can no longer benefit from the life-stealing effect of a death cape." },
  ["Deathmage"] = { description = "Your epitaph is permanently at the maximum speed.", rarity = "uncommon" },
  ["Deathstream"] = { description = "Your pervasion lifestream ability now deals poison damage to denizens instead of healing them." },
  ["Deathtempest"] = { description = "Your necromancy soulstorm ability deals additional cold damage when it profanes a denizen.", rarity = "rare" },
  ["Deliquesce"] = { description = "Commencing a new ripple will phase you out of reality for 20 seconds.", rarity = "rare" },
  ["Demagogue"] = { description = "You are immune to the disloyalty affliction.", rarity = "common" },
  ["Diagnostician"] = { description = "You are immune to the hypochondria affliction.", rarity = "uncommon" },
  ["Disciple of Celestia"] = { description = "Slaying a denizen shall restore 5% energy to your guardian angel's reserves.", rarity = "uncommon" },
  ["Disembowel"] = { description = "Your gut has a 20% chance to inflict your target with inhibit.", rarity = "uncommon" },
  ["Divine Thunder Cataclysm"] = { description = "Your Shindo thunderstorm ability now deals electric damage to all denizens in your location.", rarity = "rare" },
  ["Doom Inescapable"] = { description = "When you have sprouted tentacles, cowardly denizens will no longer be able to flee from your presence.", rarity = "common" },
  ["Draconic Rampage"] = { description = "Your draconic trample now deals a large amount of cutting damage to all denizens in your room. This effect has a 40 seconds second cooldown before it occur again.", rarity = "uncommon" },
  ["Dragonfire"] = { description = "Your draconic blast attack is imbued with a Red Dragon's breath, granting it a 20% chance to afflict your foe with inhibit.", rarity = "common" },
  ["Dragonsoul"] = { description = "Your dragon soul ignites, veiling you in draconic armour even when not a dragon.", rarity = "rare" },
  ["Dulkurio-ma"] = { description = "When you defeat a denizen, you have a 25% chance to immediately gain the favour of Matic Ridley, making your next attack guaranteed to be a high level critical hit.", rarity = "legendary" },
  ["Dulled Senses"] = { description = "The first instance of damage you suffer in a ripple will deal no damage so long as it would have done at least 25% of your health.", rarity = "uncommon" },
  ["Dungeoneer"] = { description = "Your damage dealt is increased by 5% and your balance and equilibrium recover 5% faster.", rarity = "common" },
  ["Earthen Weights"] = { description = "Your stonefist defence grants you an additional 3 strength while active.", rarity = "common" },
  ["Earthen Will"] = { description = "Gain 15% physical resistance, but lose 10% magical resistance.", rarity = "uncommon" },
  ["Earthquake"] = { description = "Your emulation upheaval ability deals significant blunt damage to all denizens in the location when it summons rubble.", rarity = "rare" },
  ["Echo of Nemuritoaure"] = { description = "You take 25% less physical damage, but falling below 35% health causes you to become transfixed and lose the benefit for 7 seconds. This can only occur once every 7 seconds.", rarity = "uncommon" },
  ["Echoing Hydra"] = { description = "When attuned to Arius, your attacks will trigger a terrible roar which strikes another random denizen in the location.", rarity = "legendary" },
  ["Elder Wisdom"] = { description = "The Jade Empress increases your intelligence by 1.", rarity = "common", echo = "The Jade Empress increases your intelligence by 2." },
  ["Elixir Addict"] = { description = "Your health elixirs are 15% more effective but you gain no health from moss or potash.", rarity = "uncommon" },
  ["Energetic"] = { description = "You are immune to lethargy and weariness.", rarity = "common" },
  ["Epidemic"] = { description = "When under the effects of death sickness, you deal 20% additional damage and your balance recovery is increased by 20%, but your ability to recover mana and health from elixirs is reduced by 50%", rarity = "rare" },
  ["Escape Artist"] = { description = "Non-boss denizens will no longer block your movements.", rarity = "uncommon" },
  ["Expansive Mind"] = { description = "Each kill on a denizen grants you 3 additional maximum mana but you lose 2 points of maximum health.", rarity = "rare", echo = "Each kill on a denizen grants you 6 additional maximum mana but you lose 4 points of maximum health." },
  ["Fae-Lapse"] = { description = "There is a 5% chance you give the denizen you are attacking amnesia. This may only occur every 5 seconds.", rarity = "uncommon", echo = "There is a 10% chance you give the denizen you are attacking amnesia. This may only occur every 5 seconds." },
  ["Falconer's Tactics"] = { description = "The cooldown for commanding your falcon to rake a denizen is reduced by 66%.", rarity = "common" },
  ["Falling Star"] = { description = "Your Saga of Ethian will now cause all non-boss denizens to flee in terror." },
  ["Feline Grace"] = { description = "Your rajamalan heritage grants you a permanent balancing defense.", rarity = "rare" },
  ["Flameheart"] = { description = "You are immune to the frozen affliction.", rarity = "uncommon" },
  ["Flashforward"] = { description = "You deal 20% bonus damage while you possess the chrono blur defence.", rarity = "common" },
  ["Flow State"] = { description = "Your acrobatics defence now conveys a 10% chance to dodge denizen attacks outright.", rarity = "legendary" },
  ["Fluid Form"] = { description = "While maintaining your watery cohesion, you take 12% reduced damage and become immune to dehydration.", rarity = "uncommon" },
  ["Font of Life"] = { description = "The Earthmother empowers your tree tattoo to now cure two afflictions.", rarity = "rare" },
  ["Forgeweaver"] = { description = "You may wear any armour regardless of class, but you lose 10% magic resistance.", rarity = "rare" },
  ["Frostbite"] = { description = "Your draconic blast attack is imbued with a Blue Dragon's breath, granting it a 20% chance to afflict your foe with aeon.", rarity = "common" },
  ["Fulcrum's Legacy"] = { description = "Your equilibrium recovers 20% faster.", rarity = "legendary", echo = "Your equilibrium recovers 25% faster." },
  ["Full Mettle Alchemist"] = { description = "While attuned to Aspar, critical strikes will restore 2% health and 2% mana.", rarity = "rare" },
  ["Furious Speed"] = { description = "The fury of the Skylord infuses you for 60 seconds at the start of each new ripple, granting you 30% increased damage, 5 additional celerity, and 20% resistance to all damage.", rarity = "legendary", echo = "The fury of the Skylord infuses you for 60 seconds at the start of each new ripple, granting you 60% increased damage and 5 additional celerity." },
  ["Fury of Ages"] = { description = "You can now use your fury ability for 45 minutes out of every hour, and it grants an additional 8 strength and 20% faster balance recovery, but endurance costs are quadrupled under its effect.", rarity = "legendary" },
  ["Gift of the Child Sorceress"] = { description = "Your deepfreeze spell can now be used against denizens and deals cold damage to all denizens in the location.", rarity = "uncommon" },
  ["Glacial Tide"] = { description = "Your pervasion saturation ability now conjures a freezing rush of water, dealing cold damage to all denizens around you.", rarity = "rare" },
  ["Good Jera"] = { description = "Jera increases your strength and constitution by an additional 1.", rarity = "common" },
  ["Grace"] = { description = "Your Tsol'aa heritage grants immunity to entanglement and webbing.", rarity = "rare" },
  ["Gravedigger"] = { description = "Your death cape can now stack up to 200% of your health.", rarity = "legendary" },
  ["Halfthought"] = { description = "While splitting your mind via the art of Kaido, your psychic resistance is increased by 25%.", rarity = "common" },
  ["Hammer and Anvil"] = { description = "The Smith's raw strength allows your attacks to bypass denizen shields.", rarity = "rare" },
  ["Hammer and Nail"] = { description = "While a sowulu rune is present, your attacks will cause damage to another random denizen in the location.", rarity = "rare" },
  ["Hardened"] = { description = "You are immune to the sensitivity affliction.", rarity = "legendary" },
  ["Haskor's Bravado"] = { description = "Your attacks have a 5% chance to afflict the target with recklessness. This may only occur every 5 seconds.", rarity = "common", echo = "Your attacks have a 10% chance to afflict the target with recklessness. This may only occur every 5 seconds." },
  ["Hawk Eyes"] = { description = "The God of War increases your chance to critically strike by 1%.", rarity = "uncommon", echo = "The God of War increases your chance to critically strike by 2%." },
  ["Herald of Infirmity"] = { description = "Your aeonics degenerate and deteriorate abilities deal 50% bonus damage against denizens.", rarity = "uncommon", echo = "Your aeonics degenerate and deteriorate abilities deal 50% bonus damage against denizens." },
  ["Heroic Strength"] = { description = "The Patron of Heroes increases your strength by 1.", rarity = "common", echo = "The Patron of Heroes increases your strength by 2." },
  ["Hexweaver"] = { description = "You no longer lose swiftcurse charges, and your curses consume no willpower.", rarity = "rare" },
  ["Hidden Gem"] = { description = "You deal 1% bonus damage.", rarity = "common", echo = "You deal 10% bonus damage." },
  ["Hoarder"] = { description = "All scaling gear effects are magnified by 15%.", rarity = "uncommon", echo = "All scaling gear effects are magnified by 30%." },
  ["Homebound"] = { description = "Returning to your raido cures you of all afflictions and restores you to full health. Not effective in the same location.", rarity = "rare" },
  ["Horror's Embrace"] = { description = "Flailing your tentacles deals damage to all denizens in your location and afflicts them with weakness. This effect has a 30 seconds cooldown before it can trigger again.", rarity = "rare" },
  ["Hot Springs"] = { description = "Casting bloodboil heals you for 25% of your maximum health and restore 5% of your willpower. This effect has a 30 seconds cooldown before it can trigger again.", rarity = "common" },
  ["Hyperfixate"] = { description = "You are immune to the confusion affliction.", rarity = "common" },
  ["Icosse's Favour"] = { description = "Begin each ripple with 8 reflections.", rarity = "uncommon" },
  ["Impetuous"] = { description = "For 60 seconds after commencing a new ripple, the Sea God will grant you 25% reduced balance and equilibrium recovery, 25% increased healing from elixirs, and 5 additional celerity.", rarity = "legendary" },
  ["Implacable"] = { description = "You are immune to the effects of fear.", rarity = "common" },
  ["Indiscriminate"] = { description = "Your Arc is now effective against denizens.", rarity = "rare" },
  ["Indomitable"] = { description = "Gain 1 points of constitution.", rarity = "common", echo = "Gain 2 points of constitution." },
  ["Inflammable"] = { description = "You are immune to burning, but suffer permanent shivering.", rarity = "rare" },
  ["Inner Spiritfire Detonation"] = { description = "Your Shindo annihilation ability now deals fire damage to all denizens in your location.", rarity = "rare" },
  ["Iron Throat"] = { description = "Gain 25% resistance to asphyxiation damage.", rarity = "common", echo = "Gain 50% resistance to asphyxiation damage." },
  ["Kevadrin's Patience"] = { description = "While you have mind cloak active, you are immune to the impatience affliction.", rarity = "rare" },
  ["Kinslayer"] = { description = "Your human heritage grants 10% more damage against other human races.", rarity = "common" },
  ["Knight's Resolve"] = { description = "While attuned to Garon, all damage you take will be reduced by an additional 10%.", rarity = "common" },
  ["Krenindalan Storm"] = { description = "Each tick of your breathstorm ability deals unblockable damage to all denizens in your location, so long as you remain within the same room.", rarity = "legendary" },
  ["Lady Luck's Legacy"] = { description = "The memory of Luckbinder grants you 3% increased critical strike chance.", rarity = "rare", echo = "The memory of Luckbinder grants you 5% increased critical strike chance." },
  ["Last Light"] = { description = "Your recital of Light shall now heal two afflictions from you, even when alone.", rarity = "uncommon" },
  ["Laurel and Stave"] = { description = "Your woeful recitation of Seleucar now lasts permanently and you deal 10% additional damage while affected.", rarity = "rare" },
  ["Legacy"] = { description = "Your attacks have a 5% chance to invoke the dazzling charisma of the Great Bard, stunning all denizens in the location for 2 seconds. This can only occur once every 5 seconds.", rarity = "rare", echo = "Your attacks have a 10% chance to invoke the dazzling charisma of the Great Bard, stunning all denizens in the location for 2 seconds. This can only occur once every 5 seconds." },
  ["Legacy of Giacinto"] = { description = "You are always under the effects of an Alchemist petrifying compound, transforming your body to iron that resists an additional 5% damage.", rarity = "uncommon" },
  ["Legacy of the Scrula"] = { description = "Parrying a limb will now parry all limbs at once.", rarity = "rare" },
  ["Legacy of the Vigil"] = { description = "Reciting the woeful tale of Tiamenjiara will cause damage to all denizens in your location, chosen randomly from cold, fire, electric, and blunt types. This effect carries a cooldown of 20 seconds.", rarity = "rare" },
  ["Legacy of the Warrior-Poet"] = { description = "You may now hamstring non-boss denizens to reduce their movement speed in chasing or wandering.", rarity = "uncommon" },
  ["Legend of Man and Blade"] = { description = "You can now enter the demon stance of Lucaine Pyramides via the DEMON command, granting you more damage than Arash, the resistances of Mir, the speed of Thyr, and the shin bonuses of Sanya all at once.", rarity = "legendary" },
  ["Legion"] = { description = "The word of power Tooros now also lays waste to denizens.", rarity = "uncommon" },
  ["Lifeseeker"] = { description = "Your guardian angel will now inform you of denizens in the current ripple when you request the seeking of presences.", rarity = "common" },
  ["Lighter Than Air"] = { description = "Your tempest defence further reduces damage taken by 10%.", rarity = "common" },
  ["Lily Pad"] = { description = "Your grook heritage causes you to always be blessed by a frogskin bubble.", rarity = "common" },
  ["Lion's Wisdom"] = { description = "You generate twice as much shin when striking your foes, and you restore 3% of your willpower when slaying a denizen.", rarity = "uncommon" },
  ["Liquidinous"] = { description = "Your balance recovers 15% faster when in a watery location.", rarity = "common" },
  ["Lithe"] = { description = "You are immune to the paralysis affliction.", rarity = "legendary" },
  ["Loquacious"] = { description = "You are immune to the stuttering affliction.", rarity = "common" },
  ["Lucid Mind"] = { description = "You are immune to the dementia affliction.", rarity = "rare" },
  ["Lycanthan Frenzy"] = { description = "Your hound deals an additional 400% damage when mauling denizens.", rarity = "uncommon" },
  ["Maklak's Promise"] = { description = "Non-boss denizens can now be impeded by icewalls.", rarity = "rare" },
  ["Maliceborn"] = { description = "Slaying a denizen will now restore 5% of your life essence.", rarity = "common" },
  ["Master of Four"] = { description = "Casting simultaneity deals four elemental bursts of damage to all denizens in your location as fire, cold, electric, and blunt damage. There is a 30 seconds cooldown before this effect can occur again.", rarity = "legendary" },
  ["Master of Harmony"] = { description = "When you defeat a denizen, you will gain a bubble of serenity for 10 seconds.", rarity = "legendary" },
  ["Matter Over Mind"] = { description = "Gain 15% increased damage but you are plagued with uncurable stupidity.", rarity = "uncommon" },
  ["Meathead"] = { description = "Your strength is increased by 5, but you suffer permanent stupidity.", rarity = "common" },
  ["Midnight Snow's Icy Heart"] = { description = "Your Shindo blizzard ability now deals cold damage to all denizens in your location.", rarity = "rare" },
  ["Might of Minia"] = { description = "Your attacks have a 5% chance to afflict the target with weakness. This may only occur every 5 seconds.", rarity = "uncommon", echo = "Your attacks have a 10% chance to afflict the target with weakness. This may only occur every 5 seconds." },
  ["Might of Sycaerunax"] = { description = "Your draconic blast ability does 25% more damage, and your breath weapon persists and will not need to be resummoned upon use.", rarity = "rare", echo = "Your draconic blast ability does 50% more damage, and your breath weapon persists and will not need to be resummoned upon use." },
  ["Mind Palace"] = { description = "While protected by a curseward, you are immune to mental afflictions.", rarity = "rare" },
  ["Miracle"] = { description = "Your class-related active curing ability now cures an additional affliction.", rarity = "uncommon" },
  ["Model Child"] = { description = "Your dwarven heritage renders you immune to mental afflictions but at the expense of all your intelligence.", rarity = "uncommon" },
  ["Morudai"] = { description = "Returning to your fulcrum cures you of all afflictions and restores you to full health. Not effective in the same location.", rarity = "rare" },
  ["Mutated Jaws"] = { description = "The cooldown for commanding your hound to maul a denizen is reduced by 66%.", rarity = "common" },
  ["Name That Tune"] = { description = "Your tune defence now provides an additional 10% damage resistance.", rarity = "uncommon" },
  ["Negotiator"] = { description = "Every fifth boon you select will grant you Prospero's Fortune, allowing you to choose a second one.", rarity = "uncommon" },
  ["Nightwalker"] = { description = "You are immune to the darkshade affliction.", rarity = "common" },
  ["Oakskin"] = { description = "Barkskin now grants an additional 10% resistance to all damage types.", rarity = "common" },
  ["Offspring's Error"] = { description = "Your grook heritage grants 3 intelligence but a 15% weakness to psychic damage.", rarity = "uncommon" },
  ["Old as Humanity"] = { description = "Your maximum age is increased by 500%.", rarity = "rare" },
  ["One Step Ahead"] = { description = "Your muscles are almost as strong as Alynzar's, and you will automatically shrug off entanglement and ropes that would bind you.", rarity = "rare" },
  ["Onyx Scales"] = { description = "Gain 15% resistance to all damage.", rarity = "rare" },
  ["Oracle"] = { description = "The Moon grants you the gift of foresight: attacks against you have a 3% chance to fully miss.", rarity = "rare" },
  ["Ormyrr Claws"] = { description = "You deal 10% bonus damage on the ground but can no longer fly.", rarity = "uncommon", echo = "You deal 20% bonus damage on the ground but can no longer fly." },
  ["Outlaw"] = { description = "You are immune to the justice and guilt afflictions.", rarity = "uncommon" },
  ["Oxygenated"] = { description = "You are immune to the asthma affliction.", rarity = "rare" },
  ["Paean"] = { description = "Defeating a denizen has a 10% chance of granting you the battlesong effect for 25 seconds.", rarity = "uncommon" },
  ["Pain Procrastinator"] = { description = "When you take damage, you will instead receive a grievous wound.", rarity = "legendary" },
  ["Panoply"] = { description = "The damage dealt by your weaving flurry ability scales directly to the number of strikes landed, randomly dealing 60% to 200% of its damage with each attack.", rarity = "rare" },
  ["Pavonian"] = { description = "Your physiology wrack ability now does unblockable damage and deals 25% more damage.", rarity = "uncommon" },
  ["Phalangite"] = { description = "Your horkvali heritage allows you to leap without using balance, but leaping costs 5% of your endurance." },
  ["Pinpoint"] = { description = "Your attacks ignore 10% of a denizen's resistances.", rarity = "uncommon", echo = "Your attacks ignore 20% of a denizen's resistances." },
  ["Plaguewalker"] = { description = "Your mhun heritage renders you immune to the effects of nausea.", rarity = "uncommon" },
  ["Plasmatic"] = { description = "You are immune to the haemophilia affliction.", rarity = "uncommon" },
  ["Poindexter"] = { description = "Your intelligence is increased by 5, but you suffer permanent dizziness.", rarity = "rare" },
  ["Pragmatic"] = { description = "You are immune to the recklessness affliction.", rarity = "legendary" },
  ["Predator"] = { description = "Cowardly denizens will no longer be able to flee from you.", rarity = "uncommon" },
  ["Preyseeker"] = { description = "Your Baalzadeen will now reveal the locations of denizens in your current ripple to you when you command it to seek out nearby presences.", rarity = "common" },
  ["Primordial Will"] = { description = "You are immune to your Elemental form's associated damage type (Fire Lords: fire, Water Lords: cold, Air Lords:asphyxiation, Earth Lords: blunt), but take 30% increased damage from the other forms' damage types.", rarity = "rare" },
  ["Prodigy"] = { description = "While wading, all of your skills are permanently transcendent.", rarity = "common" },
  ["Prophet of Creation"] = { description = "Your foresight ability now works against denizens and causes the next attack against you to miss.", rarity = "legendary" },
  ["Providence"] = { description = "Your strength, dexterity, constitution, and intelligence are each increased by 4.", rarity = "legendary" },
  ["Psiblast"] = { description = "Your draconic blast attack is imbued with a Gold Dragon's breath, granting it a 20% chance to afflict your foe with clumsiness.", rarity = "common" },
  ["Pure Mana"] = { description = "Your staffcasts cost 5% of your mana on use, dealing bonus damage equal to the amount drained.", rarity = "legendary" },
  ["Pustules"] = { description = "Your swarm sting ability now has a 50% chance to deal additional poison damage to all denizens in your location.", rarity = "uncommon" },
  ["Pyrrhic Victory"] = { description = "Your attacks against non-boss enemies always critically strike but you are now susceptible to being critically struck by denizens.", rarity = "rare" },
  ["Rage-Fuelled"] = { description = "When slaying a denizen, your next battlerage attack will cost no resource.", rarity = "rare" },
  ["Rat Catcher"] = { description = "Extispicy is now permanent and grants an additional 2% critical strike chance.", rarity = "rare" },
  ["Razor Clarity"] = { description = "You deal 50% bonus damage and have 2% bonus critical chance while benefitting from the emulation clarity defence.", rarity = "uncommon" },
  ["Razor Leaf"] = { description = "When touching your tree tattoo, razor-sharp leaves will descend upon the locale, dealing damage to all denizens present.", rarity = "uncommon" },
  ["Reaped"] = { description = "You lose all dexterity and strength but gain the putrefaction defence and you deal 200% additional damage.", rarity = "legendary" },
  ["Reaper"] = { description = "Each kill on a denizen permanently increases your damage dealt by 1%.", rarity = "legendary" },
  ["Reaver"] = { description = "You gain 4 dexterity and strength and the putrefaction defence, and you deal 200% bonus damage but your intelligence is reduced by 4.", rarity = "legendary" },
  ["Reckless Rage"] = { description = "Deal 10% more damage but you can no longer benefit from shields, prismatic barriers, or blood barriers.", rarity = "uncommon", echo = "Deal 15% more damage but you can no longer benefit from shields, prismatic barriers, or blood barriers." },
  ["Resilience of Lessers"] = { description = "While you are in lesserform (not a Dragon or Elemental Lord) gain an additional 20% resistance to all damage.", rarity = "common" },
  ["Resourceful"] = { description = "Your endurance and willpower costs are reduced by 10% and defeating a denizen restores 10% of your class resources.", rarity = "uncommon", echo = "Your endurance and willpower costs are reduced by 20% and defeating a denizen restores 20% of your class resources." },
  ["Restoral"] = { description = "You can no longer wake instantly, but when you are put to sleep, the Lady of Dreams will restore you to full health.", rarity = "rare" },
  ["Restoration"] = { description = "Restore your resources instead.", rarity = "common" },
  ["Revel in Slaughter"] = { description = "When you slay a denizen, a random affliction will be cured.", rarity = "common" },
  ["Righteous Brand"] = { description = "Your devotion penitence ability deals additional fire damage when it condemns a denizen.", rarity = "rare" },
  ["Robust Restoration"] = { description = "Your survival restoration uses 20% reduced equilibrium, restores 20% of your health, but drains 10% of your mana, willpower, and endurance.", rarity = "common" },
  ["Roll Hide"] = { description = "Tumbling out of a room will cause you to lose all pursuing denizens.", rarity = "rare" },
  ["Rose of Pain"] = { description = "Your intelligence is increased by 3, and your equilibrium recovers 15% faster, but you suffer from permanent hallucinations, and your fire resistance is reduced by 20%.", rarity = "legendary" },
  ["Rust"] = { description = "Educe Iron now deals fire damage and afflicts your foe with sensitivity.", rarity = "rare" },
  ["Sapwise"] = { description = "Your Tsol'aa heritage grants you immunity to the voyria affliction.", rarity = "common" },
  ["Savant"] = { description = "Focusing your mind has no cooldown but costs 10% of your maximum mana.", rarity = "uncommon" },
  ["Scar of Creation"] = { description = "Your scream ability has a 20% chance to afflict the target with sensitivity.", rarity = "common" },
  ["Scout's Honour"] = { description = "Activating hypersight while in a ripple hub will reveal all denizens in the current ripple to you.", rarity = "common" },
  ["Second Wind"] = { description = "Gain 1 extra life when selecting this boon, up to the maximum.", rarity = "rare" },
  ["Self-Preservation"] = { description = "You are immune to the masochism affliction.", rarity = "common" },
  ["Senseless Flurry"] = { description = "Your balance recovers 30% faster while you have the numbness defence.", rarity = "uncommon" },
  ["Serendipity"] = { description = "Your fayad heritage reduces mana costs by 25%.", rarity = "uncommon" },
  ["Serpent's Grace"] = { description = "Your weaving defence now conveys a 10% chance to dodge denizen attacks outright.", rarity = "legendary" },
  ["Serpentine"] = { description = "Gain 1 additional dexterity.", rarity = "common" },
  ["Shadow Tempo"] = { description = "Increase the bonus damage when striking denizens from the back position with bladedance attacks to 100%.", rarity = "rare" },
  ["Sharp Mind"] = { description = "Critical strikes restore 5% of your mana.", rarity = "common", echo = "Critical strikes restore 15% of your mana." },
  ["Shattered Glass"] = { description = "Defeating a denizen surrounds you in a magical shield for three seconds, but also causes you to bleed for 5% of your maximum health.", rarity = "uncommon" },
  ["Shimite's Blessing"] = { description = "While you have mutated tentacles, your attacks will cause them to strike at another denizen in the location, dealing blunt damage.", rarity = "uncommon" },
  ["Shin Enhanced"] = { description = "While in the Shin trance you gain an additional 10% resistance to fire, cold, electric, and magic damage.", rarity = "common" },
  ["Silvestri's Grace"] = { description = "Gain 3 dexterity but lose 2 constitution.", rarity = "uncommon" },
  ["Singed Flesh"] = { description = "Your attacks have a 5% chance to afflict the target with sensitivity. This may only occur every 5 seconds.", rarity = "rare", echo = "Your attacks have a 10% chance to afflict the target with sensitivity. This may only occur every 5 seconds." },
  ["Single Minded Focus"] = { description = "Gain 5% critical strike chance but you can no longer squint, glance, or observe.", rarity = "uncommon" },
  ["Sinuosity"] = { description = "Your scales reduce physical damage by an additional 15%, but your ability to resist cold is reduced by 10%.", rarity = "uncommon" },
  ["Siren's Song"] = { description = "Your attacks have a 5% chance to charm the target. This may only occur every 5 seconds.", rarity = "uncommon", echo = "Your attacks have a 10% chance to charm the target. This may only occur every 5 seconds." },
  ["Sleuth"] = { description = "Your fullsense ability will reveal all denizens in your ripple.", rarity = "uncommon" },
  ["Snowflake"] = { description = "Your constitution is increased by 5, but you suffer permanent sensitivity.", rarity = "uncommon" },
  ["Social Anxiety"] = { description = "You are immune to shyness and loneliness.", rarity = "common" },
  ["Sohtanate's Suffering"] = { description = "Focusing your mind cures two afflictions, but all stupidity you labour under shall be muddled further.", rarity = "uncommon" },
  ["Songstep"] = { description = "Your dances gain additional bonuses. Hawkstep: Gain 25% resistance to damage. Wavedance: Ignore 75% of a denizen's resistance. Harrying: Deal 50% bonus damage.", rarity = "legendary" },
  ["Sow"] = { description = "Hatred's shadow empowers your scythe and arm, causing you to strike 1 additional times with reap and cull.", rarity = "legendary" },
  ["Spark Extant"] = { description = "Your incantation now hits all enemy denizens in the location and costs 33% less willpower.", rarity = "rare" },
  ["Star of Winter"] = { description = "Entering a new ripple invokes a memory of Lifegiver, granting you 1 additional life, up to the maximum.", rarity = "legendary" },
  ["Starving"] = { description = "You are immune to the anorexia affliction.", rarity = "rare" },
  ["Statuesque"] = { description = "You are immune to the epilepsy affliction.", rarity = "rare" },
  ["Stone Stomach"] = { description = "Your tash'la heritage increases the effects of potash (not moss) by 200% and potash has a 50% reduced cooldown, but you can no longer drink health or mana.", rarity = "uncommon" },
  ["Storm Anvil"] = { description = "Your skyhammer ability is now instant and deals a large amount of electric damage to all denizens in the location.", rarity = "rare" },
  ["Timequake"] = { description = "Your aeonics distortion ability now deals magic damage to all denizens when distorting a location.", rarity = "uncommon" },
  ["Stormcleaver"] = { description = "Your bisect attack now executes denizens with less than 20% of their maximum health.", rarity = "legendary" },
  ["Stormkeeper"] = { description = "Your buffet ability now causes a bolt of lightning to strike a second nearby enemy.", rarity = "rare" },
  ["Stout"] = { description = "Your dwarven heritage grants you an additional 10% magic, fire, cold, and poison resistance.", rarity = "common" },
  ["Strength of Lessers"] = { description = "While you are in lesserform (not a Dragon or Elemental Lord) your constitution is increased by 5.", rarity = "common" },
  ["Strength of the Megalith"] = { description = "Your megalith tattoo will now additionally reduce endurance costs by 15%.", rarity = "uncommon" },
  ["Sun Sacrifice"] = { description = "Slaying a denizen shall restore 5% of your personal sunlight.", rarity = "common" },
  ["Sure-Footed"] = { description = "You are immune to the dizziness affliction.", rarity = "uncommon" },
  ["Sword of Creation"] = { description = "Your Dawnhand defence is now permanent and will always function as if it is dawn.", rarity = "common" },
  ["Tainted Grail"] = { description = "Healing elixirs heal for 10% more but any stupidity you labour under will be muddled further.", rarity = "uncommon" },
  ["Talons of Gold"] = { description = "Your eagle deals an additional 400% damage when raking denizens.", rarity = "uncommon" },
  ["Talons of Steel"] = { description = "Your falcon deals an additional 400% damage when raking denizens.", rarity = "uncommon" },
  ["Tantrum"] = { description = "Your first battlerage ability per ripple costs no rage.", rarity = "common" },
  ["Temporal Anomaly"] = { description = "The Genesis infuses your attacks with time-slowing magic, granting them a 5% chance to afflict the target with aeon. This may only occur once every 5 seconds.", rarity = "uncommon", echo = "The Genesis infuses your attacks with time-slowing magic, granting them a 10% chance to afflict the target with aeon. This may only occur once every 5 seconds." },
  ["Terror of the Skies"] = { description = "Your draconic heritage will prevent non-boss denizens from tracking or chasing you.", rarity = "rare" },
  ["The Frozen North"] = { description = "Manifesting effervescence will bring about a storm of icy vapour to assault your enemies.", rarity = "uncommon" },
  ["The Human Spirit"] = { description = "Critical strikes restore 2% of your health.", rarity = "uncommon" },
  ["The Justice That Is"] = { description = "Your confront ability has a 20% chance to afflict the target with sensitivity.", rarity = "common" },
  ["Thirst for Power"] = { description = "You deal 10% more damage when above 90% mana but 10% less damage below 90% mana.", rarity = "uncommon", echo = "You deal 20% more damage when above 90% mana but 20% less damage below 90% mana." },
  ["Thorn of the Ithmia"] = { description = "You can now use the groves thornlash ability from any location.", rarity = "uncommon" },
  ["Thunderclap"] = { description = "Your bisect ability now strikes a third time, dealing bonus electric damage to all denizens in your location.", rarity = "uncommon" },
  ["Thundercry"] = { description = "Your draconic blast attack is imbued with a Silver Dragon's breath, granting it a 20% chance to afflict your foe with fear.", rarity = "common" },
  ["Timeless Speed"] = { description = "Upon killing a denizen, you have a 10% chance of gaining the blur defence for 5 seconds.", rarity = "common" },
  ["Timequake"] = { description = "Your aeonics distortion ability now deals magic damage to all denizens when distorting a location.", rarity = "rare" },
  ["Tireless"] = { description = "Defeating a denizen will restore 2% of your willpower and 2% of your endurance.", rarity = "common" },
  ["Toxicologist"] = { description = "Your venoms now relapse against denizens, dealing damage again after a delay.", rarity = "rare" },
  ["Trenchfoot"] = { description = "Your dexterity is increased by 5, but you suffer permanent hamstrung.", rarity = "uncommon" },
  ["Truther"] = { description = "You are immune to the paranoia and hallucinations afflictions.", rarity = "common" },
  ["Tough Crowd"] = { description = "Telling a bad joke will cause psychic damage to all denizens present, but your comedic flair is so horrific that doing so will cause you to become stupid and stunned." },
  ["Elusive Foolery"] = { description = "While slippery, your dexterity is increased by 2, the defence allows you to shrug off webs, ropes, and other entanglements, but your constitution is reduced by 1." },
  ["Apostatic"] = { description = "Your priestess tarot now deals magic damage to denizens instead of healing them." },
  ["Truthseeker"] = { description = "The God of Darkness allows your eyes to perceive the truth of all hidden afflictions that may befall you.", rarity = "uncommon" },
  ["Unhurried"] = { description = "You are immune to the impatience affliction.", rarity = "legendary" },
  ["Verdant Scales"] = { description = "Gain 25% resistance to poison damage.", rarity = "common", echo = "Gain 50% resistance to poison damage." },
  ["Viridian Balm"] = { description = "While attuned to Daina, you will enjoy the effects of grove panacea, periodically healing afflictions from you.", rarity = "uncommon" },
  ["Visions of Hell"] = { description = "Laying a rite of demons deals significant psychic damage to all denizens in your location.", rarity = "uncommon" },
  ["Vitalising Tincture"] = { description = "Imbibing a nutritional formulation heals you for 33% of your maximum health. This effect has a 20 seconds cooldown before it can occur again.", rarity = "common" },
  ["Warmarch"] = { description = "Your paean refrain can now target denizens, dealing psychic damage. This damage is increased by 200%.", rarity = "common" },
  ["White Heaven's Shattered Star"] = { description = "Your multislash shall become a thing of legend, striking 3 extra times.", rarity = "legendary" },
  ["Wild Magic"] = { description = "You deal 12% increased damage, but the spells invoked by your staffcast will now be out of your control.", rarity = "uncommon" },
  ["Winter Woe"] = { description = "Summoning a blizzard through your groves snowstorm ability will deal cold damage to all denizens in your location.", rarity = "rare" },
  ["Winter's Heart"] = { description = "Your deepfreeze spell can now be used against denizens and deals cold damage to all denizens in the location.", rarity = "common" },
  ["Wisdom of Aeloratha"] = { description = "Your Viridian Form grants an additional 2 constitution and intelligence, but you take 20% more fire damage.", rarity = "rare" },
  ["Wisdom of the Ox"] = { description = "Your ox tattoo will now additionally reduce willpower costs by 15%.", rarity = "uncommon" },
  ["Worldreaver"] = { description = "Your plane-razing critical hits will now rend creation, dealing 128 x damage.", rarity = "legendary" },
  ["Wrath and Righteousness"] = { description = "When you would die, the power of Righteous Fire will allow you to restore yourself to full health and instantly slay the non-boss denizen that defeated you. This effect carries a cooldown of 1 hours.", rarity = "legendary" },
  ["Wyrmvenom"] = { description = "Your draconic blast attack is imbued with a Green Dragon's breath, granting it a 20% chance to afflict your foe with weakness.", rarity = "common" },
}

-- Merge at load. Guarded: the merge lives in 007, and a load-order change must degrade to
-- "no seed" rather than an error on every startup.
if M._boonDbMerge then
  local added, enriched = M._boonDbMerge(M.BOON_SEED)
  if added > 0 or enriched > 0 then
    M._seedAdded, M._seedEnriched = added, enriched
  end
end

